/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import org.xml.sax.Attributes;

/**
 *
 * @author blackbird
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();

        this.setTitle("Contasoft");
        this.setLocationRelativeTo(this);
        this.setResizable(false);
//       setIconImage(new ImageIcon(getClass().getResource("img/logo.png")).getImage());
//        Image icon= new Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/logo.png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void ShowPanel(JPanel p) {
        p.setSize(620, 420);
        p.setLocation(0, 0);

        this.content.removeAll();
        this.content.add(p, BorderLayout.CENTER);
        this.content.revalidate();
        this.content.repaint();
    }

    void setColor(JPanel panel) {
        panel.setBackground(new Color(165,201,202));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(57,91,100));
    }

    //metodo para llamar jpanel libro diario
    public void mostrarlibro() {
        jpLibroDiario panelLibro = new jpLibroDiario();
        this.ShowPanel(panelLibro);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jpBground = new javax.swing.JPanel();
        jpcontenido = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        btndiario = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnmayor = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btncatalogo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnintegrantes = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbliconmini = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        lblicon = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jpBground.setBackground(new java.awt.Color(255, 255, 255));

        jpcontenido.setBackground(new java.awt.Color(233, 222, 228));
        jpcontenido.setPreferredSize(new java.awt.Dimension(620, 380));

        Menu.setBackground(new java.awt.Color(57, 91, 100));
        Menu.setPreferredSize(new java.awt.Dimension(120, 420));

        btndiario.setBackground(new java.awt.Color(57, 91, 100));
        btndiario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btndiario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btndiario.setMaximumSize(new java.awt.Dimension(120, 60));
        btndiario.setMinimumSize(new java.awt.Dimension(120, 60));
        btndiario.setPreferredSize(new java.awt.Dimension(120, 60));
        btndiario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndiarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndiarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btndiarioMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(249, 245, 235));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LIBRO DIARIO");

        javax.swing.GroupLayout btndiarioLayout = new javax.swing.GroupLayout(btndiario);
        btndiario.setLayout(btndiarioLayout);
        btndiarioLayout.setHorizontalGroup(
            btndiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btndiarioLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btndiarioLayout.setVerticalGroup(
            btndiarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btndiarioLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnmayor.setBackground(new java.awt.Color(57, 91, 100));
        btnmayor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnmayor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnmayor.setMaximumSize(new java.awt.Dimension(120, 60));
        btnmayor.setMinimumSize(new java.awt.Dimension(120, 60));
        btnmayor.setPreferredSize(new java.awt.Dimension(120, 60));
        btnmayor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnmayorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnmayorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnmayorMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(249, 245, 235));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LIBRO MAYOR");

        javax.swing.GroupLayout btnmayorLayout = new javax.swing.GroupLayout(btnmayor);
        btnmayor.setLayout(btnmayorLayout);
        btnmayorLayout.setHorizontalGroup(
            btnmayorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnmayorLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnmayorLayout.setVerticalGroup(
            btnmayorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnmayorLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btncatalogo.setBackground(new java.awt.Color(57, 91, 100));
        btncatalogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btncatalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btncatalogo.setMaximumSize(new java.awt.Dimension(120, 60));
        btncatalogo.setMinimumSize(new java.awt.Dimension(120, 60));
        btncatalogo.setPreferredSize(new java.awt.Dimension(120, 60));
        btncatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncatalogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncatalogoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btncatalogoMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(249, 245, 235));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("DE CUENTAS");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(249, 245, 235));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("CATÁLOGO");

        javax.swing.GroupLayout btncatalogoLayout = new javax.swing.GroupLayout(btncatalogo);
        btncatalogo.setLayout(btncatalogoLayout);
        btncatalogoLayout.setHorizontalGroup(
            btncatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btncatalogoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(btncatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        btncatalogoLayout.setVerticalGroup(
            btncatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btncatalogoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(btncatalogoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnintegrantes.setBackground(new java.awt.Color(57, 91, 100));
        btnintegrantes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnintegrantes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnintegrantes.setMaximumSize(new java.awt.Dimension(120, 60));
        btnintegrantes.setMinimumSize(new java.awt.Dimension(120, 60));
        btnintegrantes.setPreferredSize(new java.awt.Dimension(120, 60));
        btnintegrantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnintegrantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnintegrantesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnintegrantesMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(249, 245, 235));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("INTEGRANTES");

        javax.swing.GroupLayout btnintegrantesLayout = new javax.swing.GroupLayout(btnintegrantes);
        btnintegrantes.setLayout(btnintegrantesLayout);
        btnintegrantesLayout.setHorizontalGroup(
            btnintegrantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnintegrantesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnintegrantesLayout.setVerticalGroup(
            btnintegrantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnintegrantesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbliconmini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logw.png"))); // NOI18N

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbliconmini, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btndiario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnmayor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btncatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnintegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbliconmini, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btndiario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnmayor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btncatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnintegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        content.setBackground(new java.awt.Color(249, 245, 235));
        content.setMaximumSize(new java.awt.Dimension(620, 380));
        content.setPreferredSize(new java.awt.Dimension(620, 380));

        lblicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpcontenidoLayout = new javax.swing.GroupLayout(jpcontenido);
        jpcontenido.setLayout(jpcontenidoLayout);
        jpcontenidoLayout.setHorizontalGroup(
            jpcontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpcontenidoLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpcontenidoLayout.setVerticalGroup(
            jpcontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpcontenidoLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jpcontenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpBgroundLayout = new javax.swing.GroupLayout(jpBground);
        jpBground.setLayout(jpBgroundLayout);
        jpBgroundLayout.setHorizontalGroup(
            jpBgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpcontenido, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jpBgroundLayout.setVerticalGroup(
            jpBgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpcontenido, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndiarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndiarioMouseEntered
        if (btndiario.getBackground().getRGB() == -15574355)
            setColor(btndiario);
    }//GEN-LAST:event_btndiarioMouseEntered

    private void btndiarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndiarioMouseExited
//        if (this.btndiario.getBackground().getRGB() != -15574355)
//        resetColor(btndiario);

    }//GEN-LAST:event_btndiarioMouseExited

    private void btndiarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndiarioMousePressed
        setColor(btndiario);
        resetColor(btnintegrantes);
        resetColor(btnmayor);
        resetColor(btncatalogo);
        // Abrir sección
        jpCrearLibro panelLibroDiario = new jpCrearLibro();
        this.ShowPanel(panelLibroDiario);
    }//GEN-LAST:event_btndiarioMousePressed

    private void btnmayorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmayorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmayorMouseEntered

    private void btnmayorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmayorMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmayorMouseExited

    private void btnmayorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmayorMousePressed
        setColor(btnmayor);
        resetColor(btndiario);
        resetColor(btnintegrantes);
        resetColor(btncatalogo);
        // Abrir sección
        jpLibroMayor panelLibroMayor = new jpLibroMayor();
        this.ShowPanel(panelLibroMayor);
    }//GEN-LAST:event_btnmayorMousePressed

    private void btncatalogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncatalogoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btncatalogoMouseEntered

    private void btncatalogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncatalogoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btncatalogoMouseExited

    private void btncatalogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncatalogoMousePressed
        // TODO add your handling code here:

        setColor(btncatalogo);
        resetColor(btndiario);
        resetColor(btnmayor);
        resetColor(btnintegrantes);
        // Abrir sección
        jpCatalogo panelCatalogo = new jpCatalogo();
        this.ShowPanel(panelCatalogo);

    }//GEN-LAST:event_btncatalogoMousePressed

    private void btnintegrantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnintegrantesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnintegrantesMouseEntered

    private void btnintegrantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnintegrantesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnintegrantesMouseExited

    private void btnintegrantesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnintegrantesMousePressed
            setColor(this.btnintegrantes);
            resetColor(btndiario);
            resetColor(btnmayor);
            resetColor(btncatalogo);
        // Abrir sección
        jpIntegrantes inte = new jpIntegrantes();
        this.ShowPanel(inte);
    }//GEN-LAST:event_btnintegrantesMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel btncatalogo;
    private javax.swing.JPanel btndiario;
    private javax.swing.JPanel btnintegrantes;
    private javax.swing.JPanel btnmayor;
    private javax.swing.JPanel content;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jpBground;
    private javax.swing.JPanel jpcontenido;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel lbliconmini;
    // End of variables declaration//GEN-END:variables
}
