/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Conexion.conexion;
import Entidades.libroDiario;
import java.awt.BorderLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan
 */
public class jpCrearLibro extends javax.swing.JPanel {
    /**
     * Creates new form jpCrearLibro
     */
    public int nLibro;
       conexion conectO;
    DefaultTableModel modelo = new DefaultTableModel();
      libroDiario libD ;
    public jpCrearLibro() {
        initComponents();   
         libD = new libroDiario();
         conectO = new conexion();
         this.mostrarLibros();
         this.btnGenerarAsiento.setEnabled(false);
    }
//frmPrincipal p = new frmPrincipal();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nameEmpresa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fInicio = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        fFin = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        btnGenerarAsiento = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setMaximumSize(new java.awt.Dimension(620, 420));
        setMinimumSize(new java.awt.Dimension(620, 420));
        setPreferredSize(new java.awt.Dimension(620, 420));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin.setBackground(new java.awt.Color(249, 245, 235));
        admin.setMaximumSize(new java.awt.Dimension(620, 420));
        admin.setMinimumSize(new java.awt.Dimension(620, 420));
        admin.setPreferredSize(new java.awt.Dimension(620, 420));
        admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable (int row, int col){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionForeground(new java.awt.Color(165, 201, 202));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        admin.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 231, 620, 170));

        jLabel1.setBackground(new java.awt.Color(57, 91, 100));
        jLabel1.setForeground(new java.awt.Color(57, 91, 100));
        jLabel1.setText("Nombre de la empresa");
        admin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        admin.add(nameEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 214, -1));

        jLabel2.setBackground(new java.awt.Color(57, 91, 100));
        jLabel2.setForeground(new java.awt.Color(57, 91, 100));
        jLabel2.setText("Fecha de operación:");
        admin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        admin.add(fInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 130, -1));

        jLabel3.setBackground(new java.awt.Color(57, 91, 100));
        jLabel3.setForeground(new java.awt.Color(57, 91, 100));
        jLabel3.setText("Inicio:");
        admin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        admin.add(fFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 130, -1));

        jLabel4.setBackground(new java.awt.Color(57, 91, 100));
        jLabel4.setForeground(new java.awt.Color(57, 91, 100));
        jLabel4.setText("Fin:");
        admin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        btnGenerarAsiento.setForeground(new java.awt.Color(0, 102, 102));
        btnGenerarAsiento.setText("Generar Asiento");
        btnGenerarAsiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGenerarAsientoMousePressed(evt);
            }
        });
        btnGenerarAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarAsientoActionPerformed(evt);
            }
        });
        admin.add(btnGenerarAsiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        btnEliminar.setForeground(new java.awt.Color(0, 102, 102));
        btnEliminar.setText("Eliminar libro");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        admin.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        btnAgregar.setForeground(new java.awt.Color(0, 102, 102));
        btnAgregar.setText("Agregar Libro");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        admin.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 420));

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents

    public void limpiarCampos(){
        this.nameEmpresa.setText(null);
        this.fFin.setCalendar(null);
        this.fInicio.setCalendar(null);

    }
    public void mostrarLibros(){
        try {
             modelo.setColumnCount(0);
          modelo.setRowCount(0);

             this.jTable1.setModel(modelo);
            ResultSet rst = conectO.consultaRegistros("select id_libro, nombre_empresa,fecha_inicio,fecha_fin from libroDiario;");  
            modelo.addColumn("N° Libro");
            modelo.addColumn("Empresa");
            modelo.addColumn("Fecha de Inicio");
            modelo.addColumn("Fecha de Fin");
            while (rst.next()) {   
                
             Object[] data= {rst.getString("id_libro"),rst.getString("nombre_empresa"),
                 rst.getString("fecha_inicio"),rst.getString("fecha_fin")};                
                modelo.addRow(data);               
            }          
        } catch (SQLException e) {
            System.out.println(e);
            
        }
    }
    private void btnGenerarAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarAsientoActionPerformed
        frmAsiento as = new frmAsiento(this.nLibro);
        System.out.println(this.nLibro);
        as.setVisible(true);
    }//GEN-LAST:event_btnGenerarAsientoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
      SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String empresa = this.nameEmpresa.getText().trim();
        String fechaI = ((JTextField) this.fInicio.getDateEditor().getUiComponent()).getText();
        String fechaF = ((JTextField) this.fFin.getDateEditor().getUiComponent()).getText();
        try {
            Date fI = formato.parse(fechaI);
            Date fF = formato.parse(fechaF);
          
            if (fI.equals(fF) || fI.before(fF)) {
                if (empresa.length() > 0 && fechaI.getBytes().length > 9 && fechaF.getBytes().length > 9) {

                    libD.setEmpresa(empresa);
                    libD.setF_fin(fechaF);
                    libD.setF_inicio(fechaI);

                    libD.aggLibro();
                    this.mostrarLibros();
                    this.limpiarCampos();
                } else {

                    JOptionPane.showMessageDialog(null, "Por favor llene los campos de manera correcta", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Por favor ingrese fechas válidas", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ParseException ex) {
            Logger.getLogger(jpCrearLibro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGenerarAsientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarAsientoMousePressed
       
    }//GEN-LAST:event_btnGenerarAsientoMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
          libD.deleteLibro(nLibro);
        this.mostrarLibros();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
           int index = this.jTable1.getSelectedRow();
        this.nLibro = Integer.parseInt((String) this.jTable1.getValueAt(index, 0));
        if (nLibro >0){
            this.btnGenerarAsiento.setEnabled(true);
        }
        
    }//GEN-LAST:event_jTable1MouseClicked
    
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerarAsiento;
    private com.toedter.calendar.JDateChooser fFin;
    private com.toedter.calendar.JDateChooser fInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameEmpresa;
    // End of variables declaration//GEN-END:variables
}
