/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Conexion.conexion;
import Entidades.libroDiario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import reportes.prueba;

/**
 *
 * @author blackbird
 */
public class jpLibroMayor extends javax.swing.JPanel {

    /**
     * Creates new form jpLibroMayor
     */
    
    conexion conectO;
    DefaultTableModel modelo = new DefaultTableModel();

    int id;
      libroDiario libD ;
    public jpLibroMayor() {
        initComponents();
         libD = new libroDiario();
         conectO = new conexion();
         this.jTable1.setModel(modelo);
  
         this.mostrarLibros();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        admin.setBackground(new java.awt.Color(204, 204, 255));
        admin.setMaximumSize(new java.awt.Dimension(620, 380));
        admin.setPreferredSize(new java.awt.Dimension(620, 380));
        admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable (int row, int col){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        admin.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 600, 110));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Seleccione un libro:");
        admin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Mayorización");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        admin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Balance de comprobación");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        admin.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Generar documentos:");
        admin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Libro diario");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        admin.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int index = this.jTable1.getSelectedRow();
         this.id = Integer.parseInt(this.jTable1.getValueAt(index, 0).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         if(this.id !=0 ){
              
             try {
            JasperReport jr = null;
             String path = "src\\reportes\\report1.jasper";
           
            Map Parameter = new HashMap();
        
           
             Parameter.put("id_libro", this.id);
      
            jr =(JasperReport)JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(jr,Parameter,conectO.ConnecrDB());
            JasperViewer jv =new JasperViewer(jp,false);
            jv.setVisible(true);
            jv.setTitle(path);
           
            
            
            } catch (JRException ex) {
                Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, "hola", ex);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
            }

         }
         else{
                
                     JOptionPane.showMessageDialog(null,"selecione un libro!!");///
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if(this.id !=0 ){              
             try {
                 
            JasperReport jr = null;
             String path = "src\\reportes\\report2.jasper";
            
            Map Parameter = new HashMap();        
           
             Parameter.put("libro_id", this.id);        
            
            jr =(JasperReport)JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(jr,Parameter,conectO.ConnecrDB());
            JasperViewer jv =new JasperViewer(jp,false);
            jv.setVisible(true);
            jv.setTitle(path);
          
            
            
            } catch (JRException ex) {
               // Logger.getLogger(Prueba.class.getName()).log(Level.SEVERE, "hola", ex);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
            }

         }
         else{
                    JOptionPane.showMessageDialog(null,"selecione un libro!!");///
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         
         if(this.id !=0 ){            
             try {
            JasperReport jr = null;
             String path = "src\\reportes\\report_Asientos.jasper";
            
            Map Parameter = new HashMap();
        
           
             Parameter.put("libro_id", this.id);
        
            
            jr =(JasperReport)JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(jr,Parameter,conectO.ConnecrDB());
            JasperViewer jv =new JasperViewer(jp,false);
            jv.setVisible(true);
            jv.setTitle(path);
            
            
            
            } catch (JRException ex) {
               // Logger.getLogger(Prueba.class.getName()).log(Level.SEVERE, "hola", ex);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
            }

         }
         else{
                     JOptionPane.showMessageDialog(null,"selecione un libro!!");///
         }
          
        //  Logger.getLogger(Prueba.class.getName()).log(Level.SEVERE, null, ex);
          //  Logger.getLogger(Prueba.class.getName()).log(Level.SEVERE, null, ex);
        
///muestra el id del libro

    }//GEN-LAST:event_jButton3ActionPerformed

 public void mostrarLibros(){
        try {
             modelo.setColumnCount(0);
          modelo.setRowCount(0);
            
            ResultSet rst = conectO.consultaRegistros("select id_libro, nombre_empresa,fecha_inicio,fecha_fin from libroDiario;");  
            modelo.addColumn("N° Libro");
            modelo.addColumn("Empresa");
            modelo.addColumn("Fecha de Inicio");
            modelo.addColumn("Fecha de Fin");
            while (rst.next()) {   
                
             Object[] data= {rst.getString("id_libro"),rst.getString("nombre_empresa"),
                 rst.getString("fecha_inicio"),rst.getString("fecha_fin")};                
                modelo.addRow(data);               
            }          
        } catch (SQLException e) {
            System.out.println(e);
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
